name: Tests
on: [ pull_request, push ]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install -U setuptools pip
          python -m pip install -U poetry
      - name: Set-up Poetry
        run: |
          poetry install --with test
      - name: Tests
        run: "python -m pytest"
